export const experiences = [
  {
    id: '1',
    role: 'Desenvolvedor front-end',
    company: 'Ton | Stone Co.',
    location: 'São Paulo, SP',
    time: 'dez de 2021 – até o momento',
    url: 'https://ton.com.br',
  },
  {
    id: '2',
    role: 'Desenvolvedor front-end',
    company: 'Coderockr',
    location: 'Joinville, SC',
    time: 'set de 2020 – dez de 2021',
    url: 'https://coderockr.com/',
  },
  {
    id: '3',
    role: 'Desenvolvedor mobile',
    company: 'Clickweb',
    location: 'Londrina, PR',
    time: 'jul de 2020 – ago de 2020',
    url: 'https://www.clickweb.com.br/',
  },
  {
    id: '4',
    role: 'Desenvolvedor full stack',
    company: 'Digital One',
    location: 'Cianorte, PR',
    time: 'out de 2019 – jun de 2020',
    url: 'https://www.digitalone.com.br/',
  },
  {
    id: '5',
    role: 'Suporte técnico',
    company: 'SisTerra',
    location: 'Cianorte, PR',
    time: 'fev de 2018 – out de 2019',
    url: 'https://www.sisterra.com.br/',
  },
]
